#index:
#    path: /
#    controller: App\Controller\DefaultController::index
form_submit:
  path: /form-submit
  controller: App\Controller\FormController::submit
login_submit:
  path: /login-submit
  controller: App\Controller\UserController::login
recipe_submit:
    path: /recipe-submit
    controller: App\Controller\RecipeController::submitRecipe

